version: "3.8"

services:  
  ace_server:
    image: ${ACE_IMAGE_BASE}:${ACE_VERSION}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_HOSTNAME}
    restart: unless-stopped
    ports:
      - "${ACE_ADMIN_REST_API_EXTERNAL_PORT}:7600"
      - "${ACE_HTTP_EXTERNAL_PORT}:7800"
      - "${ACE_HTTPS_EXTERNAL_PORT}:7843"
    environment:
      LICENSE: ${LICENSE}
      ACE_SERVER_NAME: ${ACE_SERVER_NAME}

 
networks:
  default:
    name: ismf_network
    external: true

