version: "3.8"

services:  
  ace_server:
    image: ${ACE_IMAGE_BASE}:${ACE_VERSION}
    container_name: ${CONTAINER_NAME}
    hostname: ${CONTAINER_HOSTNAME}
    restart: unless-stopped
    ports:
      - "${ACE_ADMIN_REST_API_EXTERNAL_PORT}:${ACE_ADMIN_REST_API_INTERNAL_PORT}"
      - "${ACE_HTTP_EXTERNAL_PORT}:${ACE_HTTP_INTERNAL_PORT}"
      - "${ACE_HTTPS_INTERNAL_PORT}:${ACE_HTTPS_INTERNAL_PORT}"
    environment:
      LICENSE: ${LICENSE}
      ACE_SERVER_NAME: ${ACE_SERVER_NAME}
      ACE_WORKPATH: ${ACE_WORKPATH}

 
networks:
  default:
    name: ismf_network
    external: true

